image: python:3.10.2


stages:
  - check

include:
  - project: 'gl.devops/cicd-template'
    ref: master
    file:
      - '/common/verify-commit-email/.gitlab-ci.yml'
      - '/common/commitlint/.gitlab-ci.yml'
      - '/common/sonarqube/.gitlab-ci.yml'
